/**
 * 命令 ID 常量表。
 * 所有菜单、快捷键、上下文动作都应优先复用这里的稳定标识，
 * 避免字符串散落在各个模块里。
 */
export const COMMAND_IDS = Object.freeze({
    APP_ABOUT: 'app.about',
    APP_QUIT: 'app.quit',
    APP_OPEN: 'app.open',
    APP_OPEN_FILE: 'app.openFile',
    APP_OPEN_FOLDER: 'app.openFolder',
    APP_SETTINGS: 'app.settings',
    THEME_TOGGLE: 'theme.toggle',
    EDITOR_UNDO: 'editor.undo',
    EDITOR_REDO: 'editor.redo',
    EDITOR_FIND: 'editor.find',
    EDITOR_SELECT_ALL: 'editor.selectAll',
    EDITOR_CUT: 'editor.cut',
    EDITOR_COPY: 'editor.copy',
    EDITOR_PASTE: 'editor.paste',
    EDITOR_SELECT_SEARCH_MATCHES: 'editor.selectSearchMatches',
    DOCUMENT_SAVE: 'document.save',
    DOCUMENT_CLOSE_TAB: 'document.closeTab',
    DOCUMENT_NEW_UNTITLED: 'document.newUntitled',
    DOCUMENT_NEW_FILE: 'document.newFile',
    DOCUMENT_COPY_MARKDOWN: 'document.copyMarkdown',
    DOCUMENT_DELETE: 'document.delete',
    DOCUMENT_MOVE: 'document.move',
    DOCUMENT_RENAME: 'document.rename',
    WORKSPACE_CREATE_FILE: 'workspace.createFile',
    WORKSPACE_CREATE_FOLDER: 'workspace.createFolder',
    WORKSPACE_RENAME_ENTRY: 'workspace.renameEntry',
    WORKSPACE_MOVE_ENTRY: 'workspace.moveEntry',
    WORKSPACE_DELETE_ENTRY: 'workspace.deleteEntry',
    WORKSPACE_COPY_PATH: 'workspace.copyPath',
    WORKSPACE_REVEAL_IN_FINDER: 'workspace.revealInFinder',
    WORKSPACE_RUN_ENTRY: 'workspace.runEntry',
    VIEW_TOGGLE_SIDEBAR: 'view.toggleSidebar',
    VIEW_TOGGLE_STATUS_BAR: 'view.toggleStatusBar',
    VIEW_TOGGLE_SOURCE_MODE: 'view.toggleSourceMode',
    TOOLBAR_TOGGLE_MARKDOWN: 'toolbar.toggleMarkdown',
    FEATURE_TERMINAL_TOGGLE: 'feature.terminal.toggle',
    FEATURE_TERMINAL_SHOW_HISTORY: 'feature.terminal.showHistory',
    FEATURE_AI_TOGGLE: 'feature.ai.toggle',
    FEATURE_SCRATCHPAD_TOGGLE: 'feature.scratchpad.toggle',
    FEATURE_TOC_TOGGLE: 'feature.toc.toggle',
    EXPORT_IMAGE: 'export.currentView.image',
    EXPORT_PDF: 'export.currentView.pdf',
    RECENT_OPEN_ENTRY: 'recent.openEntry',
    RECENT_CLEAR: 'recent.clear',
    APP_CHECK_UPDATE: 'app.checkUpdate',
});
